# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=100)),
                ('_id', models.IntegerField()),
                ('long_desc_html', models.CharField(max_length=1000)),
                ('seller_thumb_url', models.CharField(max_length=1000)),
                ('resource_types', models.CharField(max_length=1000)),
                ('content_type', models.IntegerField()),
                ('long_desc', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('greads_review_url', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('edm_score', models.FloatField()),
                ('avg_rating', models.FloatField()),
                ('creation_date', models.CharField(max_length=1000)),
            ],
        ),
    ]
