# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='Inappropriate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_info',
            name='not_helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_info',
            name='spam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_info',
            name='wrong_tags',
            field=models.IntegerField(default=0),
        ),
    ]
