# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0004_auto_20160401_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='greads_review_url',
        ),
    ]
